check50:
  files: &check50_files
    - !exclude "*"
    - !include "*.c"
    - !include "*.h"
    - !require dictionary.c
    - !require dictionary.h

submit50:
  files: *check50_files
  remote:
    message: "Go to https://speller.cs50.io/challenge/{commit_hash} to see your results!"
    callback: "https://speller.cs50.io/challenge"

cevsubmit:
  files: *check50_files
